---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jonepwzx/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R videos $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH