---
deployment:
 tasks:
 - export DEPLOYPATH=/home/jonepxzx/public_html/
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp style.css $DEPLOYPATH                   #copy all recursively to $DEPLOYPATH
        
        
